services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    restart: always
    environment: 
      SA_PASSWORD: "@Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports: 
      - "1433:1433" 

# user sa
# pass @Password123